config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'game/index'

  root 'welcome#index'
  get 'game/edit'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  end

  def edit

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/game/_game.html.erb
<script>
  window.onload = function () {

    var game = new Phaser.Game(innerWidth, innerHeight, Phaser.canvas, '');

    game.state.add('Boot', Game.Boot);
    game.state.add('Preloader', Game.Preloader);
    game.state.add('MainMenu', Game.MainMenu);
    game.state.add('Level1', Game.Level1);

    game.state.start('Boot');


  };
</script>

app/views/game/_index.html.erb
<script>
  var game = new Phaser.Game(innerWidth, innerHeight, Phaser.CANVAS, 'phaser-example', {
    preload: preload,
    create: create,
    update: update
  });

  function preload() {
    game.load.image('board_tile', '<%= asset_path('board_tile') %>');
    game.load.image('reward_smile', '<%= asset_path('reward_smile') %>');
    game.load.image('background_space', '<%= asset_path('Background.png') %>');
    game.load.image('spaceship', '<%= asset_path('Space_Ship.png') %>');
    game.load.image('toilet', '<%= asset_path('Toilet.png') %>');
    game.load.image('star01', '<%= asset_path('star.svg') %>');
  }

  // Look at asset URL helper in Rails, image URL

  var spaceship;

  function create() {

    // create board assets
    game.stage.backgroundColor = '#FFFFFF';
    var background = game.add.sprite(0, 0, 'background_space');

    // create game assets
    var spaceship = new GamePiece('spaceship', 15, 75);

    var toilet = new GamePiece('toilet', 5, 175);

    var star = new GamePiece('star01', 5, 250);

    var smile = new GamePiece('reward_smile', 15, 15);

    var heart_sketch = [
      '................',
      '................',
      '................',
      '.000.......0000.',
      '003300...0003300',
      '0333300.00333330',
      '0333330003333330',
      '0333333333333300',
      '.03333333333330.',
      '.00333333333300.',
      '..033333333300..',
      '...0333333300...',
      '...003333300....',
      '....0333300.....',
      '.....03300......',
      '......000.......'
    ];


    game.create.texture('heart', heart_sketch, 4, 4, 0);

    var heart = new GamePiece('heart', 15, 400);


    // Temp working section



    // ***************************************************************
    // ********** Rough Save Data Code *******************************

    heart.object.events.onDragStop.add(onDragStop, this);



    // Test the heart movement, and saving the position data (for saved game)
    var heartPrintout;
    var heartPos = [];
    var heartJSON;

    // concept function for when a token or game piece is dropped after a drag.
    // Should kick off the position data saving

    function onDragStop() {
      heartPrintout = "(" + heart.x + ", " + heart.y + "), ";
      console.log(heartPrintout);
      $('#Heart_Pos').append(heartPrintout);

      // create an array for JSON file
      heartPos = [{"x": heart.x, "y": heart.y}];
     // console.log(heartPos);
      heartJSON = JSON.stringify(heartPos);
      console.log(heartJSON);


      // I don't have this array to JSON parsing down yet.
      // When I do, I expect JSON to a rails DB via AJAX is a good way to store board piece postiion info.
//      var heartJSON = JSON.parse(heartPosJSON.toString(''));
//      var stringyJSON = JSON.stringify(heartJSON.push);
    }

  }

  function update() {

  }

</script>
<p>Move the Heart, and watch the position update here</p>
<p id="Heart_Pos">Heart Position (x,y): </p>

app/views/game/index.html.erb
<%= render partial: "index" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhaserOnRails02</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Kiddo Moto</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<%= root_path %>">Home</a></li>
      <li><a href="<%= game_index_path %>">Game</a></li>
      <li><a href="<%= game_edit_path %>">Edit Game</a></li>
      <li><a href="#">Login</a></li>
    </ul>
  </div>
</nav>

<div class="container-fluid">

  <%= yield %>

</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class='row'>
  <div class='jumbotron'>
    <div class='text-center'>
      <div class="row">
        <h1>Kiddo Moto</h1>
      </div>
      <div class="row">
        <h2>A Motivational Game For Children</h2>
      </div>
    </div>
  </div>
</div>